name: test
on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - "*"
jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        go_version:
          - '1.24'
    name: Test with ${{ matrix.go_version }}
    steps:
      - uses: actions/checkout@v4
      - name: Install Go ${{ matrix.go_version }}
        uses: actions/setup-go@v5
        with:
          go-version: ${{ matrix.go_version }}
          check-latest: true
      - name: Vet and test
        run: |
          go version
          go vet ./...
          go test ./...
  golangci:
    name: Linting
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'
          check-latest: true
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          args: "--config .golangci.yml"
